spring:
  config:
    import:
      - optional:classpath:application-secret.yml

  application:
    name: refit-backend

  jpa:
    open-in-view: false

  profiles:
    active: prod
    include:
    - oauth2